# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfTQp0ukgJr8-jP-btgwwAXgJ_D-fUxr
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. GENERATE SECURE, SYNTHETIC DATA
np.random.seed(42)
data = {
    'Age': np.random.randint(22, 60, 500),
    'Department': np.random.choice(['Sales', 'Engineering', 'HR'], 500),
    'MonthlyIncome': np.random.randint(4000, 15000, 500),
    'JobSatisfaction': np.random.randint(1, 5, 500),
    'Attrition': np.random.choice(['Yes', 'No'], 500, p=[0.16, 0.84])
}
df = pd.DataFrame(data)

# 2. BASIC DATA ANALYSIS
print("--- HR Attrition Analysis ---")
print(f"Total Employees Analyzed: {len(df)}")

attrition_counts = df['Attrition'].value_counts()
attrition_rate = (attrition_counts['Yes'] / len(df)) * 100
print(f"Overall Attrition Rate: {attrition_rate:.1f}%\n")

income_comparison = df.groupby('Attrition')['MonthlyIncome'].mean().round(2)
print("Average Monthly Income by Attrition Status:")
print(income_comparison)

# 3. DATA VISUALIZATION
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
sns.boxplot(x='Attrition', y='MonthlyIncome', data=df, palette='Set2')
plt.title('Monthly Income vs. Attrition')

plt.subplot(1, 2, 2)
sns.countplot(x='JobSatisfaction', hue='Attrition', data=df, palette='Set1')
plt.title('Job Satisfaction vs. Attrition')

plt.tight_layout()
plt.savefig('hr_attrition_dashboard.png')
print("\nAnalysis complete! Visualizations saved as 'hr_attrition_dashboard.png'.")